---
driver:
  name: docker
  <% if (RUBY_PLATFORM =~ /darwin/) %>
  socket: <%= "#{ENV['DOCKER_HOST']}" %>
  docker_path: /usr/local/bin/docker
  <% else %>
  docker_path: /usr/bin/docker'
  <% end %>
  forward_agent: true
  require_chef_omnibus: 12.5
  disable_upstart: false
  use_cache: false
  remove_images: true

provisioner:
  name: chef_zero
  environments_path: test/integration/default/environments
  data_bags_path: test/integration/default/data_bags
  client_rb:
    environment: dev
  attributes:
    jlsolrcloud:
      fluentd:
        # The file does not need to be a valid JAR file.
        # This will enable fluentd configuration but solr will (fail and) skip
        # configuration at start time.
        source: 'https://www.google.com'

platforms:
  - name: ubuntu-14.04

suites:
  # For running locally, the bootstrap cookbook will install zookeeper also in
  # the test environment. Needs to use vagrant / virtualbox as Docker does not
  # handle restarting the solr process correctly
  - name: default
    driver:
      name: vagrant
    run_list:
      - recipe[jlsolrcloud_bootstrap::default]
    attributes:
      jlsolrcloud:
        zkhosts:
          - localhost:2181
 # This suite is run on a private jenkins server
  - name: jenkins
    run_list:
      - recipe[jlsolrcloud::default]
    attributes:
     jlsolrcloud:
       # Normally set zkhosts in a wrapper cookbook
       zkhosts:
         - zookeeper:2181
    # As defined in docker-compose.yml
    driver:
      links:
        - chefjlsolrcloud_zookeeper_1:zookeeper
