driver:
  name: dokken
  chef_version: 14.11.21

transport:
  name: dokken

provisioner:
  name: dokken
  environments_path: test/integration/environments
  data_bags_path: test/integration/data_bags
  client_rb:
    environment: dev
  attributes:
    jlsolrcloud:
      fluentd:
        # The file does not need to be a valid JAR file.
        # This will enable fluentd configuration but solr will (fail and) skip
        # fluentd logging configuration at start time.
        source: 'https://www.google.com'
      remote_jmx: true
      zkhosts:
        - localhost:2181

platforms:
  - name: ubuntu-18.04
    driver:
      intermediate_instructions:
        # Note that kitchen-dokken will only run this once when it first pulls
        # down the image, if you have this cached and it's old you'll probably
        # get errors from apt
        - RUN apt-get update
      image: dokken/ubuntu-18.04
      privileged: true
      pid_one_command: /bin/systemd
      volume:
        - '/sys/fs/cgroup:/sys/fs/cgroup:ro'

verifier:
  name: inspec
  inspec_tests:
    - 'test/integration/default'

suites:
  # For running locally, the bootstrap cookbook will install zookeeper also in
  # the test environment. Needs to use vagrant / virtualbox as Docker does not
  # handle restarting the solr process correctly
  - name: default
    run_list:
      - recipe[jlsolrcloud_bootstrap::default]
    # As defined in docker-compose.yml
    driver:
      links:
        - chefjlsolrcloud_zookeeper_1:zookeeper
