name             'jlsolrcloud'
maintainer       'James Legg'
maintainer_email 'mail@jameslegg.co.uk'
license          'Apache 2.0'
description      'Installs/Configures solrcloud'
long_description 'Installs/Configures solrcloud 5'
version          '1.1.2'
supports         'ubuntu'
depends          'java'
depends          'apt'
depends          'clocker', '~> 0.3'
