name             'jlsolrcloud'
maintainer       'James Legg'
maintainer_email 'mail@jameslegg.co.uk'
license          'Apache 2.0'
description      'Installs/Configures solrcloud'
long_description 'Installs/Configures solrcloud 5'
version          '0.7.3'
supports         'ubuntu'
depends          'java'
depends          'logrotate'
depends          'apt'
depends          'clocker', '~> 0.3'
