name             'jlsolrcloud_bootstrap'
maintainer       'Conversocial'
maintainer_email 'aaron@conversocial.com'
license          'All rights reserved'
description      'Installs/Configures jlsolrcloud_bootstrap'
long_description 'Installs/Configures jlsolrcloud_bootstrap'
version          '0.1.0'
supports         'ubuntu'

depends 'jlsolrcloud'
depends 'conv_zookeeper', '~> 2.0'
