name             'jlsolrcloud_bootstrap'
maintainer       'Conversocial'
maintainer_email 'aaron@conversocial.com'
license          'All rights reserved'
description      'Installs/Configures jlsolrcloud_bootstrap'
long_description 'Installs/Configures jlsolrcloud_bootstrap'
version          '0.1.0'
supports         'ubuntu'
depends          'jlsolrcloud'
depends          'conv_zookeeper', '~> 1.1.1'
depends          'java'
depends          'logrotate'
depends          'apt'
depends          'clocker', '~> 0.3'

